# Generated by Django 5.2.4 on 2025-07-16 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='config_added',
            field=models.BooleanField(default=False),
        ),
    ]
