# Generated by Django 5.2.4 on 2025-07-17 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_uploadedfile_config_added'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='folder',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='uploadedfile',
            name='uploaded_at',
        ),
        migrations.AddField(
            model_name='folder',
            name='allowed_type',
            field=models.CharField(choices=[('csv', 'CSV'), ('pdf', 'PDF')], default='csv', max_length=10),
        ),
    ]
