# Generated by Django 5.2.4 on 2025-07-17 09:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0003_remove_folder_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='folder',
            name='allowed_type',
            field=models.CharField(choices=[('pdf', 'PDF'), ('csv', 'CSV')], default='csv', max_length=10),
        ),
        migrations.AlterField(
            model_name='uploadedfile',
            name='folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='files.folder'),
        ),
    ]
