# Generated by Django 5.2.4 on 2025-07-22 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0004_alter_folder_allowed_type_alter_uploadedfile_folder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='folder',
            name='allowed_type',
            field=models.CharField(choices=[('pdf', 'PDF'), ('csv', 'CSV'), ('json', 'JSON')], default='csv', max_length=10),
        ),
    ]
