# Generated by Django 4.2.7 on 2025-09-10 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0006_folder_created_at_folder_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='chunk_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='has_chunks',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='has_config',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='has_inference',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='processing_hash',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='processing_status',
            field=models.CharField(choices=[('raw', 'Raw'), ('processing', 'Processing'), ('processed', 'Processed'), ('error', 'Error')], default='raw', max_length=20),
        ),
        migrations.AlterField(
            model_name='folder',
            name='allowed_type',
            field=models.CharField(choices=[('pdf', 'PDF'), ('csv', 'CSV'), ('json', 'JSON'), ('parquet', 'PARQUET')], default='csv', max_length=10),
        ),
        migrations.AlterField(
            model_name='folder',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='folder',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='uploadedfile',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
