# Generated by Django 5.2.4 on 2025-09-18 07:24

import files.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0007_uploadedfile_chunk_count_uploadedfile_has_chunks_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedfile',
            name='file',
            field=models.FileField(upload_to=files.models.get_upload_path),
        ),
    ]
