# Generated by Django 4.2.7 on 2025-09-18 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0008_alter_uploadedfile_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='folder',
            name='is_public',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='uploadedfile',
            name='is_public',
            field=models.BooleanField(default=True),
        ),
    ]
