# Generated by Django 4.2.7 on 2025-09-29 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0009_make_files_public_by_default'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='folder',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='uploadedfile',
            options={'ordering': ['-uploaded_at']},
        ),
        migrations.AlterField(
            model_name='folder',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='uploadedfile',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
    ]
